version: '3'
services:
  mariadb:
    container_name: mariadb
    platform: linux/x86_64
    image: mariadb:10.5
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    platform: linux/x86_64
    image: prestashop/prestashop:1.7.8.10-apache
    restart: unless-stopped
    ports:
      - 443:443
      - 8080:80
    volumes:
      - ./src:/var/www/html
    environment:
      - PS_DEV_MODE=1

    depends_on:
      - mariadb
    networks:
      - prestashop_network

networks:
  prestashop_network:
